---
title: "Data Import"
author: "Teresa Del Bianco"
date: "`r Sys.Date()`"
output: html_document
---

# Load packages 

```{r, messtp = FALSE, warning = FALSE, include = FALSE}
packs <- c("R.matlab", "reshape2", "dplyr", "multidplyr", "tidyr")
lapply(packs, require, character.only = TRUE)
```

# Read data from matlab (? Hz)

```{r}
cbfnp_matlabFile  <- readMat('Data/Matfiles/50faces_results_20200410T181246.mat')
str(cbfnp_matlabFile)
```

# AOI = Face

```{r}
datList <- cbfnp_matlabFile$tempScores[[1]][[1]][,,5]
# summary(datList)
```
```{r}
datList.un <- lapply(datList, unlist)
ids <- unlist(cbfnp_matlabFile$tempScores[[2]][[1]][,,1]$ids)

time <- cbfnp_matlabFile$tempScores[[2]][[1]][,,1]$time
# summary(datList.un)
# str(datList.un)
```
```{r}
data_c <- as.data.frame(datList.un[[2]])
```
```{r}
names(data_c) <- ids
```
```{r}
data_c$time <- time
```
```{r}
data_c$aoi.name <- datList.un[[1]][,1]
```
```{r}
head(data_c[,c(1,ncol(data_c)-1,ncol(data_c))])
```

## Format data

```{r}
# names(data)
data_c_long <- melt(data_c,
        # ID variables - all the variables to keep but not split apart on
        id.vars=c("time"),
        # The source columns
        # measure.vars=c("control", "cond1", "cond2" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
        variable.name="id",
        value.name="face.plt"
        )
# str(data_c_long)
```
```{r}
data_c_long <- data_c_long %>% mutate(id=gsub(pattern = "#BASELINE",
                               replacement = "",
                               x = id))
```

```{r}
head(data_c_long)
```

# AOI = Body

```{r}
datList <- cbfnp_matlabFile$tempScores[[1]][[1]][,,6]
# summary(datList)
```
```{r}
datList.un <- lapply(datList, unlist, use.names=FALSE)
ids <- unlist(cbfnp_matlabFile$tempScores[[2]][[1]][,,1]$ids)
time <- cbfnp_matlabFile$tempScores[[2]][[1]][,,1]$time
# summary(datList.un)
# str(datList.un)
```
```{r}
data_b <- as.data.frame(datList.un[[2]])
```
```{r}
names(data_b) <- ids
```
```{r}
data_b$time <- time
```
```{r}
data_b$aoi.name <- datList.un[[1]][,1]
```
```{r}
head(data_b[,c(1,ncol(data_b)-1,ncol(data_b))])
```

### Format data

```{r}
# names(data)
data_b_long <- melt(data_b,
        # ID variables - all the variables to keep but not split apart on
        id.vars=c("time"),
        # The source columns
        # measure.vars=c("control", "cond1", "cond2" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
        variable.name="id",
        value.name="body.plt"
        )
# str(data_b_long)
```
```{r}
data_b_long <- data_b_long %>% mutate(id=gsub(pattern = "#BASELINE",
                               replacement = "",
                               x = id))
head(data_b_long)
```

# AOI = Background People

```{r}
datList <- cbfnp_matlabFile$tempScores[[1]][[1]][,,7]
# summary(datList)
```
```{r}
datList.un <- lapply(datList, unlist, use.names=FALSE)
ids <- unlist(cbfnp_matlabFile$tempScores[[2]][[1]][,,1]$ids)
time <- cbfnp_matlabFile$tempScores[[2]][[1]][,,1]$time
# summary(datList.un)
# str(datList.un)
```
```{r}
data_bp <- as.data.frame(datList.un[[2]])
```
```{r}
names(data_bp) <- ids
```
```{r}
data_bp$time <- time
```
```{r}
data_bp$aoi.name <- datList.un[[1]][,1]
```
```{r}
head(data_bp[,c(1,ncol(data_bp)-1,ncol(data_bp))])
```

### Format data

```{r}
# names(data)
data_bp_long <- melt(data_bp,
        # ID variables - all the variables to keep but not split apart on
        id.vars=c("time"),
        # The source columns
        # measure.vars=c("control", "cond1", "cond2" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
        variable.name="id",
        value.name="bg.plt"
        )
# str(data_b_long)
```
```{r}
data_bp_long <- data_bp_long %>% mutate(id=gsub(pattern = "#BASELINE",
                               replacement = "",
                               x = id))
head(data_bp_long)
```

# Merge datasets

```{r}
# dim(data_c_long)
# dim(data_b_long)
```

```{r}
# cbfnp <- rbind(data_c_long, data_b_long, data_bp_long)
cbfnp <- data_c_long %>%
  left_join(data_b_long, by=c("id", "time")) %>%
  left_join(data_bp_long, by=c("id", "time")) %>%
  mutate_at(vars(face.plt, body.plt, bg.plt), as.numeric)
```

## Non-aoi looks

```{r}
cbfnp.wide <- cbfnp %>%
  mutate(plt.null=ifelse(face.plt==0 & body.plt==0 & bg.plt==0, 1, 
                         ifelse(is.na(face.plt) & is.na(body.plt) & is.na(bg.plt), NA, 0)))
```

```{r}
cbfnp <- melt(cbfnp.wide,
        # ID variables - all the variables to keep but not split apart on
        id.vars=c("time", "id"),
        # The source columns
        # measure.vars=c("control", "cond1", "cond2" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
        variable.name="aoi.name",
        value.name="plt"
        ) %>%
  mutate(aoi.name=gsub(pattern = ".plt", replacement = "", x = aoi.name))
```


```{r}
rm(list=setdiff(ls(), ls(pattern = c("cbfnp"))))
```

# Attach demographic data

```{r}
demo_t1 <- read.csv("Data/Datasets/LEAP_t1_Core clinical variables_03-09-19-withlabels_&Inc,Ethn.csv")
demo_t2 <- read.csv("Data/Datasets/LEAP_t2_Core clinical variables_20-03-19-withlabels.csv")
```

```{r}
demo_t1_ft <- demo_t1 %>%
  select(subjects, 
         t1_group,t1_diagnosis, 
         t1_site,
         t1_schedule_adj, t1_sex, t1_ageyrs, t1_fsiq,
         t1_srs_tscore, t1_vabsdscoresc_dss, t1_vabsdscoress_dss) %>%
  rename(id=subjects) %>%
  mutate_at(vars(7:11), funs( ifelse (. >=500, NA, .))) %>%
  mutate(id=as.factor(as.character(id)),
         t1_diagnosis=ifelse(t1_group=="TD", "NT", "AUT"),
         tp=1)
  # mutate_at(vars(2:3), funs( ifelse (. =="TD" | . =="Control", "NT", paste(.)))) 

colnames(demo_t1_ft) <- sub("t1_", "", colnames(demo_t1_ft))

demo_t2_ft <- demo_t2 %>%
  select(subjects,
         t2_ageyrs,
         t2_srs_tscore, t2_vabsdscoresc_dss, t2_vabsdscoress_dss) %>%
  rename(id=subjects) %>%
  mutate_at(vars(2:5), funs( ifelse (. >=500, NA, .))) %>%
  mutate(tp=2,
         id=as.factor(as.character(id))
         )

colnames(demo_t2_ft) <- sub("t2_", "", colnames(demo_t2_ft))
```

For now, I only add demo at tp 1 to the et data. 


```{r}
cbfnp.demo <- left_join(cbfnp, demo_t1_ft, by="id")
head(cbfnp.demo)
```

```{r}
save(cbfnp.demo, file = "Data/SavedWS/ns-ff-demo-leap.RData")
save(demo_t1_ft, demo_t2_ft, file = "Data/SavedWS/demo-leap.RData")
```











