---
title: "Data Import NANS"
author: "Teresa Del Bianco"
date: "`r Sys.Date()`"
output: html_document
---

This script is importing the raw data comprising NAs (at the sample level). We extract the proportion of valid trials per task and save it into the object pNA. 

# Load packages 

```{r, messtp = FALSE, warning = FALSE, include = FALSE}
packs <- c("R.matlab", "reshape2", "dplyr", "multidplyr", "ggplot2", "tidyr")
lapply(packs, require, character.only = TRUE)
```

# Read data from matlab (? Hz)

```{r}
cbfnp_matlabFile  <- readMat('Matfiles/50faces_results_20200410T181246.mat')
# str(cbfnp_matlabFile)
```

# Trial 1

```{r}
datList <- cbfnp_matlabFile$tempScores[[2]][[1]][,,1]
# summary(datList)
```
```{r}
datList.un <- lapply(datList, unlist, use.names=FALSE)
ids <- datList.un$ids
time <- datList.un$time
# summary(datList.un)
# str(datList.un)
```
```{r}
data_missing <- as.data.frame(datList.un$missing)
data_absent <- as.data.frame(datList.un$absent)
```
```{r}
names(data_missing) <- ids
names(data_absent) <- ids
```
```{r}
data_missing$time <- time
data_absent$time <- time
```

## Format data

### Missing

```{r}
# names(data)
data_missing_long <- melt(data_missing,
        # ID variables - all the variables to keep but not split apart on
        id.vars=c("time"),
        # The source columns
        # measure.vars=c("control", "cond1", "cond2" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
        variable.name="id",
        value.name="missing"
        )
# str(data_c_long)
```
```{r}
data_missing_long <- data_missing_long  %>% mutate(id=gsub(pattern = "#BASELINE",
                               replacement = "",
                               x = id))
```

### Absent

```{r}
# names(data)
data_absent_long <- melt(data_absent,
        # ID variables - all the variables to keep but not split apart on
        id.vars=c("time"),
        # The source columns
        # measure.vars=c("control", "cond1", "cond2" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
        variable.name="id",
        value.name="absent"
        )
# str(data_c_long)
```
```{r}

data_absent_long <- data_absent_long  %>% mutate(id=gsub(pattern = "#BASELINE",
                               replacement = "",
                               x = id))
```


## Merge Missing and Absent

```{r}
data_miss_abs <- left_join(data_missing_long, data_absent_long, by=c("id", "time"))
```

# Add scenes

# Add Scenes

```{r}
scenes <- read.csv("Datasets/scenes.csv") %>%
  dplyr::select(begin_time_ss.msec, end_time_ss.msec, scene)
head(scenes)
```
```{r}
data_miss_abs.s <- data_miss_abs %>% 
  mutate(scene=case_when(time>=scenes[1,1] & time<=scenes[1,2] ~ scenes[1,3],
                         time>=scenes[2,1] & time<=scenes[2,2] ~ scenes[2,3],
                         time>=scenes[3,1] & time<=scenes[3,2] ~ scenes[3,3],
                         time>=scenes[4,1] & time<=scenes[4,2] ~ scenes[4,3],
                         time>=scenes[5,1] & time<=scenes[5,2] ~ scenes[5,3],
                         time>=scenes[6,1] & time<=scenes[6,2] ~ scenes[6,3],
                         time>=scenes[7,1] & time<=scenes[7,2] ~ scenes[7,3],
                         time>=scenes[8,1] & time<=scenes[8,2] ~ scenes[8,3],
                         time>=scenes[9,1] & time<=scenes[9,2] ~ scenes[9,3],
                         time>=scenes[10,1] & time<=scenes[10,2] ~ scenes[10,3],
                         time>=scenes[11,1] & time<=scenes[11,2] ~ scenes[11,3],
                         time>=scenes[12,1] & time<=scenes[12,2] ~ scenes[12,3],
                         time>=scenes[13,1] & time<=scenes[13,2] ~ scenes[13,3],
                         time>=scenes[14,1] & time<=scenes[14,2] ~ scenes[14,3]),
         f_on=ifelse(is.na(scene), 0, 1))
head(data_miss_abs.s)
```
# Look at the missing data

```{r}
data_miss_abs %>%
  filter(absent==1 & missing==1) #ok
```

```{r}
not_pres <- data_miss_abs.s %>%
  filter(absent==1) %>%
  distinct(id, time, scene, f_on, absent)
head(not_pres)
```

```{r}
load("SavedWS/demo-leap.RData")
```

```{r}
p_NA <- data_miss_abs.s %>%
  group_by(id, scene, f_on) %>%
  summarise(pNA=sum(missing==1)/n()*100) %>%
  left_join(demo_t1_ft[,c("id", "diagnosis", "site", "ageyrs", "schedule_adj", "fsiq")], by="id")
head(p_NA)
```

```{r}
to_excl <- p_NA %>%
  filter(pNA>=75)  

to_excl %>% group_by(diagnosis) %>% summarise(N=n())
```
```{r}
save(data_miss_abs.s, p_NA, to_excl, not_pres, file="SavedWS/NA_info.RData")
```