---
title: "Descriptive Statistics"
author: "Teresa Del Bianco"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
# Load packages
packs <- c("reshape2", "dplyr", "ggplot2", "knitr", "tidyr", "ggpubr")
lapply(packs, require, character.only = TRUE)
```

```{r, include=FALSE}
# Read Data 
load("Data/SavedWS/data-model.RData")
```

# Descriptive Statistics

```{r}
data.aggr.05.clean2.ext <- filter(data.aggr.05.clean2.ext, scene!="L2")
```

# Raw Data Plots

```{r, warning=FALSE}
ts.raw.all <- data.aggr.05.clean2.ext %>%
  group_by(id, diagnosis, sex, epoch.05) %>%
  summarise(m=mean(m.plt, na.rm=TRUE),
            s=sd(m.plt, na.rm=TRUE),
            n=n(),
            error=qnorm(0.975)*s/sqrt(n),
            left=m-error,
            right=m+error) 
ts.raw.avg <- data.aggr.05.clean2.ext %>%
  group_by(diagnosis, sex, epoch.05) %>%
  summarise(m=mean(m.plt, na.rm=TRUE),
            s=sd(m.plt, na.rm=TRUE),
            n=n(),
            error=qnorm(0.975)*s/sqrt(n),
            left=m-error,
            right=m+error)
```

```{r}
ts.raw.plot.m1 <- ggplot(data = ts.raw.avg %>% filter(diagnosis=="NT")) +
  geom_ribbon(aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=sex),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(aes(x = epoch.05, y = m, col = sex)) +
  
  # facet_grid(~diagnosis) +
  labs(x = "Time (s)", y = "PLT", subtitle = "NT Set (Model 1)") +
  scale_color_manual(values = c("#E69F00","#009E73"), name="Sex") +
  ylim(0,1) +
  theme(legend.position = "top")
ts.raw.plot.m1
# ggsave(filename = "Plots/raw-m1.pdf", plot = ts.raw.plot.m1)
```
```{r}
ts.raw.plot.m2 <- ggplot(data = ts.raw.avg %>% filter(diagnosis=="AUT")) +
  geom_ribbon(aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=sex),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(aes(x = epoch.05, y = m, col = sex)) +
  
  # facet_grid(~diagnosis) +
  labs(x = "Time (s)", y = "PLT", subtitle = "AUT Set (Model 2)") +
  scale_color_manual(values = c("#E69F00","#009E73"), name="Sex") +
  ylim(0,1) +
  theme(legend.position = "top")
ts.raw.plot.m2
# ggsave(filename = "Plots/raw-m2.pdf", plot = ts.raw.plot.m2)
```
```{r}
ts.raw.plot.m3 <- ggplot(data = ts.raw.avg %>% filter(sex=="Male")) +
  geom_ribbon(aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=diagnosis),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(aes(x = epoch.05, y = m, col = diagnosis)) +
  
  # facet_grid(~diagnosis) +
  labs(x = "Time (s)", y = "PLT", subtitle = "Male Set (Model 3)") +
  scale_color_manual(values = c("#D55E00", "#F0E442"), name="Diagnosis") +
  ylim(0,1) +
  theme(legend.position = "top")
ts.raw.plot.m3
# ggsave(filename = "Plots/raw-m3.pdf", plot = ts.raw.plot.m3)
```

```{r}
ts.raw.plot.m4 <- ggplot(data = ts.raw.avg %>% filter(sex=="Female")) +
  geom_ribbon(aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=diagnosis),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(aes(x = epoch.05, y = m, col = diagnosis)) +
  
  # facet_grid(~diagnosis) +
  labs(x = "Time (s)", y = "PLT", subtitle = "Female Set (Model 4)") +
  scale_color_manual(values = c("#D55E00", "#F0E442"), name="Diagnosis") +
  ylim(0,1) +
  theme(legend.position = "top")
ts.raw.plot.m4
# ggsave(filename = "Plots/raw-m12.pdf", plot = ts.raw.plot.m12)
```

```{r}
library(patchwork)
comb <- ts.raw.plot.m1 + ts.raw.plot.m2 +  ts.raw.plot.m3 + ts.raw.plot.m4 & theme(legend.position = "top", 
                                                         legend.direction = "horizontal", 
                                                         legend.box = "horizontal"
                                                         ) 
comb <- comb + plot_layout(ncol=4, guides="collect")
# ggsave(filename = "Plots/raw-m1234.pdf", plot = comb, height = 7, width = 14)
```

# Z-Scores

```{r}
m.nt <- data.aggr.05.clean2.ext %>%
  filter(diagnosis=="NT") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  as.data.frame() %>%
  summarise(m=round(mean(m.plt), 2)) 
m.aut <- data.aggr.05.clean2.ext %>%
  filter(diagnosis=="AUT") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  as.data.frame() %>%
  summarise(m=round(mean(m.plt), 2)) 
m.m <- data.aggr.05.clean2.ext %>%
  filter(sex=="Male") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  as.data.frame() %>%
  summarise(m=round(mean(m.plt), 2)) 
m.f <- data.aggr.05.clean2.ext %>%
  filter(sex=="Female") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  as.data.frame() %>%
  summarise(m=round(mean(m.plt), 2)) 
ts.raw.avg.znt <- data.aggr.05.clean2.ext %>%
  filter(diagnosis=="NT") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  mutate(z.plt=m.plt-m.nt$m) %>%
  group_by(sex, epoch.05) %>%
  summarise(m=mean(z.plt, na.rm=TRUE),
            s=sd(z.plt, na.rm=TRUE),
            n=n(),
            error=qnorm(0.975)*s/sqrt(n),
            left=m-error,
            right=m+error) 
ts.raw.avg.zaut <- data.aggr.05.clean2.ext %>%
  filter(diagnosis=="AUT") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  mutate(z.plt=m.plt-m.aut$m) %>%
  group_by(sex, epoch.05) %>%
  summarise(m=mean(z.plt, na.rm=TRUE),
            s=sd(z.plt, na.rm=TRUE),
            n=n(),
            error=qnorm(0.975)*s/sqrt(n),
            left=m-error,
            right=m+error) 
ts.raw.avg.zm <- data.aggr.05.clean2.ext %>%
  filter(sex=="Male") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  mutate(z.plt=m.plt-m.m$m) %>%
  group_by(diagnosis, epoch.05) %>%
  summarise(m=mean(z.plt, na.rm=TRUE),
            s=sd(z.plt, na.rm=TRUE),
            n=n(),
            error=qnorm(0.975)*s/sqrt(n),
            left=m-error,
            right=m+error) 
ts.raw.avg.zf <- data.aggr.05.clean2.ext %>%
  filter(sex=="Female") %>%
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  mutate(z.plt=m.plt-m.f$m) %>%
  group_by(diagnosis, epoch.05) %>%
  summarise(m=mean(z.plt, na.rm=TRUE),
            s=sd(z.plt, na.rm=TRUE),
            n=n(),
            error=qnorm(0.975)*s/sqrt(n),
            left=m-error,
            right=m+error) 
```

```{r}
ts.raw.zs.nt <- ggplot() +
  geom_hline(yintercept = 0, col="black", linetype="dashed") +
  geom_ribbon(
    data = ts.raw.avg.znt,
    aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=sex),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(data = ts.raw.avg.znt,
            aes(x = epoch.05, y = m, col = sex)) +
  
  # facet_grid(~diagnosis) +
  labs(x = "Time in Scene (s)", y = "Proportional Looking Time - Z-Score", subtitle = "Model 1 (non-Autistic)") +
  scale_color_manual(values = c("#E69F00","#009E73"), name="Sex") +
  # ylim(0,1) +
  theme(legend.position = "top",
        text=element_text(size=18)) +
  ylim(-1,1)
ts.raw.zs.nt
```
```{r}
ts.raw.zs.aut <- ggplot() +
  geom_hline(yintercept = 0, col="black", linetype="dashed") +
  geom_ribbon(
    data = ts.raw.avg.zaut,
    aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=sex),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(data = ts.raw.avg.zaut,
            aes(x = epoch.05, y = m, col = sex)) +
  
  # facet_grid(~t1_group) +
  labs(x = "Time in Scene (s)", y = "", subtitle = "Model 2 (Autistic)") +
  scale_color_manual(values = c("#E69F00","#009E73"), name="Sex") +
  # ylim(0,1) +
  theme(legend.position = "top",
        text=element_text(size=18)) +
  ylim(-1,1)
ts.raw.zs.aut
```

```{r}
ts.raw.zs.m <- ggplot() +
  geom_hline(yintercept = 0, col="black", linetype="dashed") +
  geom_ribbon(
    data = ts.raw.avg.zm,
    aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=diagnosis),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(data = ts.raw.avg.zm,
            aes(x = epoch.05, y = m, col = diagnosis)) +
  
  # facet_grid(~t1_group) +
  labs(x = "Time in Scene (s)", y = "", subtitle = "Model 3 (males)") +
  scale_color_manual(values = c("#D55E00","#F0E442"), name="Group") +
  # ylim(0,1) +
  theme(legend.position = "top",
        text=element_text(size=18)) +
  ylim(-1,1)

ts.raw.zs.m
```
```{r}
ts.raw.zs.f <- ggplot() +
  geom_hline(yintercept = 0, col="black", linetype="dashed") +
  geom_ribbon(
    data = ts.raw.avg.zf,
    aes(ymin = left,
        ymax = right,
        x = epoch.05,
        group=diagnosis),
    alpha = 0.7,
    fill = "grey"
  ) +
  # stat_summary(data = ts.raw.avg,
  #              aes(x = epoch.05, y = m), 
  #              fun = "mean", colour = "black", geom = "line") +
  geom_path(data = ts.raw.avg.zf,
            aes(x = epoch.05, y = m, col = diagnosis))  +
  
  # facet_grid(~t1_group) +
  labs(x = "Time in Scene (s)", y = "", subtitle = "Model 4 (females)") +
  scale_color_manual(values = c("#D55E00","#F0E442"), name="Group") +
  ylim(-1,1) +
  theme(legend.position = "top",
        text=element_text(size=18))
ts.raw.zs.f
```

```{r}
library(patchwork)
comb.z <- ts.raw.zs.nt + ts.raw.zs.aut + ts.raw.zs.m + ts.raw.zs.f & theme(legend.position = "top", 
                                                         legend.direction = "horizontal", 
                                                         legend.box = "horizontal"
                                                         ) 
comb.z <- comb.z + plot_layout(ncol=4, guides="collect")
comb.z
# ggsave(filename = "Plots/raw-zs-m1234.pdf", plot = comb.z, height = 7, width = 14)
```

# Missing Data

```{r}
miss <- data.aggr.05.clean2.ext %>% 
  mutate(diagnosis=ifelse(diagnosis=="NT", "non-Autistic", "Autistic")) %>%
  group_by(diagnosis, sex) %>%
  summarise(N=n(),
    m.pNA=round(mean(pNA, na.rm=TRUE)*100, 2),
            s.pNA=round(sd(pNA, na.rm=TRUE)*100, 2))
```

```{r}
f_d <- subset(miss, sex=="Female")
smean <- function(x) {
  sc <- x[, grepl( "^m." , names(x))]
  return(sc)
}
sc <- smean(f_d)

ssd <- function(x) {
  ss <- x[, grepl( "^s." , names(x))]
  return(ss)
}
ss <- ssd(f_d)

mdiff <- function(x) {
  md <- head(x, -1) - tail(x, -1)
  return(md)
  }
md <- mdiff(sc)

p_sd <- function(x) {
  #sqrt(((N1-1)s1 + (N2-1)s2)/(N1+N2)-2)
  DF_1 <- subset(x, select = N)[1,] -1
  DF_2 <- subset(x, select = N)[2,] -1
  
  s_1 <- DF_1*(ss[1,2]^2)
  s_2 <- DF_2*(ss[1,2]^2)
  
  sm <- s_1 + s_2
  
  den <- (subset(x, select = N)[1,] + subset(x, select = N)[2,])-2
  
  pSD <- sqrt(sm / den)
  
  return(pSD)
}

pSD <- p_sd(f_d)

es <- function(x, y) {
  #c_es = md / pSD
  c_es <- abs(x / y)
  return(c_es)
}

c_es_f <- es(md, pSD)
```

```{r}
m_d <- subset(miss, sex=="Male")
smean <- function(x) {
  sc <- x[, grepl( "^m." , names(x))]
  return(sc)
}
sc <- smean(m_d)

ssd <- function(x) {
  ss <- x[, grepl( "^s." , names(x))]
  return(ss)
}
ss <- ssd(m_d)

mdiff <- function(x) {
  md <- head(x, -1) - tail(x, -1)
  return(md)
  }
md <- mdiff(sc)

p_sd <- function(x) {
  #sqrt(((N1-1)s1 + (N2-1)s2)/(N1+N2)-2)
  DF_1 <- subset(x, select = N)[1,] -1
  DF_2 <- subset(x, select = N)[2,] -1
  
  s_1 <- DF_1*(ss[1,2]^2)
  s_2 <- DF_2*(ss[2,2]^2)
  
  sm <- s_1 + s_2
  
  den <- (subset(x, select = N)[1,] + subset(x, select = N)[2,])-2
  
  pSD <- sqrt(sm / den)
  
  return(pSD)
}

pSD <- p_sd(m_d)

es <- function(x, y) {
  #c_es = md / pSD
  c_es <- abs(x / y)
  return(c_es)
}

c_es_m <- es(md, pSD)
```

```{r}
c_es <- rbind(c_es_f, c_es_m)
```

```{r}
nt_d <- subset(miss, diagnosis=="non-Autistic")
smean <- function(x) {
  sc <- x[, grepl( "^m." , names(x))]
  return(sc)
}
sc <- smean(nt_d)

ssd <- function(x) {
  ss <- x[, grepl( "^s." , names(x))]
  return(ss)
}
ss <- ssd(nt_d)

mdiff <- function(x) {
  md <- head(x, -1) - tail(x, -1)
  return(md)
  }
md <- mdiff(sc)

p_sd <- function(x) {
  #sqrt(((N1-1)s1 + (N2-1)s2)/(N1+N2)-2)
  DF_1 <- subset(x, select = N)[1,] -1
  DF_2 <- subset(x, select = N)[2,] -1
  
  s_1 <- DF_1*(ss[1,2]^2)
  s_2 <- DF_2*(ss[2,2]^2)
  
  sm <- s_1 + s_2
  
  den <- (subset(x, select = N)[1,] + subset(x, select = N)[2,])-2
  
  pSD <- sqrt(sm / den)
  
  return(pSD)
}

pSD <- p_sd(nt_d)

es <- function(x, y) {
  #c_es = md / pSD
  c_es <- abs(x / y)
  return(c_es)
}

c_es_nt <- es(md, pSD)
```

```{r}
aut_d <- subset(miss, diagnosis=="Autistic")
smean <- function(x) {
  sc <- x[, grepl( "^m." , names(x))]
  return(sc)
}
sc <- smean(aut_d)

ssd <- function(x) {
  ss <- x[, grepl( "^s." , names(x))]
  return(ss)
}
ss <- ssd(aut_d)

mdiff <- function(x) {
  md <- head(x, -1) - tail(x, -1)
  return(md)
  }
md <- mdiff(sc)

p_sd <- function(x) {
  #sqrt(((N1-1)s1 + (N2-1)s2)/(N1+N2)-2)
  DF_1 <- subset(x, select = N)[1,] -1
  DF_2 <- subset(x, select = N)[2,] -1
  
  s_1 <- DF_1*(ss[1,2]^2)
  s_2 <- DF_2*(ss[2,2]^2)
  
  sm <- s_1 + s_2
  
  den <- (subset(x, select = N)[1,] + subset(x, select = N)[2,])-2
  
  pSD <- sqrt(sm / den)
  
  return(pSD)
}

pSD <- p_sd(aut_d)

es <- function(x, y) {
  #c_es = md / pSD
  c_es <- abs(x / y)
  return(c_es)
}

c_es_aut <- es(md, pSD)
```

```{r}
c_es <- rbind(c_es_nt, c_es_aut)
```
